# Generated by Django 4.2.17 on 2024-12-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bedsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('4x6', '4x6'), ('5x6', '5x6'), ('6x6', '6x6')], max_length=10)),
                ('material', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('white', 'White'), ('light-blue', 'Light Blue'), ('brown', 'Brown')], default='white', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='bedding/bedsheets/')),
            ],
        ),
        migrations.CreateModel(
            name='Duvet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('4x6', '4x6'), ('5x6', '5x6'), ('6x6', '6x6')], max_length=10)),
                ('material', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('white', 'White'), ('light-blue', 'Light Blue'), ('brown', 'Brown')], default='white', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='bedding/duvets/')),
            ],
        ),
        migrations.CreateModel(
            name='Mattress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('plain', 'Plain Mattress'), ('quilted', 'Quilted Mattress')], max_length=10)),
                ('size', models.CharField(choices=[('3.5x6', '3.5 x 6 (42 x 74 inches)'), ('4x6', '4 x 6 (48 x 74 inches)'), ('5x6', '5 x 6 (60 x 74 inches)'), ('6x6', '6 x 6 (72 x 74 inches)')], max_length=5)),
                ('thickness', models.PositiveIntegerField(choices=[(6, '6 inch'), (8, '8 inch'), (10, '10 inch'), (12, '12 inch')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='mattresses/')),
            ],
        ),
        migrations.CreateModel(
            name='Pillow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('pair', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='bedding/pillows/')),
            ],
        ),
    ]
