# Generated by Django 4.2.17 on 2025-01-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netsapp', '0009_order_billing_email_order_billing_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_phone',
        ),
    ]
