# Generated by Django 4.2.17 on 2025-02-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netsapp', '0011_cartitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
    ]
